spring.application.name=banco-xyz-migracion-batch
server.port=8081

# --- H2 (comentado: descomentar este bloque y comentar Oracle para usarlo) ---
# spring.datasource.url=jdbc:h2:file:./data/bancoxyz;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.sql.init.platform=h2
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

# --- Oracle Autonomous (activo para la entrega de la semana 3) ---
spring.datasource.url=jdbc:oracle:thin:@miquintabd_tp?TNS_ADMIN=C:/Users/lisbe/OneDrive/Escritorio/backend_semana_5/Wallet_miQuintaBD
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=ADMIN
spring.datasource.password=OracleCloud123
spring.sql.init.platform=oracle
spring.sql.init.separator=/
spring.batch.jdbc.isolation-level-for-create=READ_COMMITTED
spring.h2.console.enabled=false

# --- PostgreSQL (opcional) ---
# spring.datasource.url=jdbc:postgresql://localhost:5432/bancoxyz
# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.datasource.username=postgres
# spring.datasource.password=postgres
# spring.sql.init.platform=postgresql
# spring.h2.console.enabled=false

spring.sql.init.mode=always
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false

bancoxyz.archivo.transacciones=classpath:data/transacciones.csv
bancoxyz.archivo.intereses=classpath:data/intereses.csv
bancoxyz.archivo.cuentas-anuales=classpath:data/cuentas_anuales.csv

# Particiones (clase RutaExpress + PDF ): gridSize alineado al pool
bancoxyz.particion.grid-size=3
bancoxyz.particion.core-pool-size=3
bancoxyz.particion.max-pool-size=3
bancoxyz.particion.queue-capacity=10

# Extra profesor S3: local | remoto-particion | remoto-chunk
# local = TaskExecutor (nota 7). remoto-particion = canal de mensajes.
# remoto-chunk = el maestro lee y el worker procesa/escribe el chunk.
bancoxyz.escalado.modo=local

# Observabilidad (Micrometer / Actuator)
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}

logging.level.org.springframework.batch=INFO
logging.level.cl.duoc.bancoxyz=INFO
