-- Requiere spring.sql.init.platform=oracle y spring.sql.init.separator=/
-- (ver application.properties, bloque ORACLE). El "/" en su propia linea le
-- indica a Spring donde termina cada bloque, igual que en SQL*Plus.

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE transaccion_procesada';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE resumen_transacciones';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE interes_procesado';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE movimiento_anual';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE estado_cuenta_anual';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE transaccion_procesada (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaccion_id  NUMBER         NOT NULL,
    fecha           DATE           NOT NULL,
    monto           NUMBER(12, 2)  NOT NULL,
    tipo            VARCHAR2(20)   NOT NULL,
    estado          VARCHAR2(20)   NOT NULL,
    observacion     VARCHAR2(255),
    CONSTRAINT uq_transaccion_procesada_id UNIQUE (transaccion_id)
)
/

CREATE TABLE resumen_transacciones (
    id                   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_proceso        TIMESTAMP      NOT NULL,
    total_validas        NUMBER         NOT NULL,
    total_debitos        NUMBER(14, 2)  NOT NULL,
    total_creditos       NUMBER(14, 2)  NOT NULL,
    cantidad_debitos     NUMBER         NOT NULL,
    cantidad_creditos    NUMBER         NOT NULL,
    job_execution_id     NUMBER,
    CONSTRAINT uq_resumen_transacciones_job UNIQUE (job_execution_id)
)
/

CREATE TABLE interes_procesado (
    id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id          NUMBER         NOT NULL,
    nombre             VARCHAR2(100)  NOT NULL,
    saldo_inicial      NUMBER(14, 2)  NOT NULL,
    edad               NUMBER         NOT NULL,
    tipo               VARCHAR2(20)   NOT NULL,
    tasa_aplicada      NUMBER(6, 4)   NOT NULL,
    interes_calculado  NUMBER(14, 2)  NOT NULL,
    saldo_final        NUMBER(14, 2)  NOT NULL,
    estado             VARCHAR2(20)   NOT NULL,
    CONSTRAINT uq_interes_procesado_cuenta UNIQUE (cuenta_id)
)
/

CREATE TABLE movimiento_anual (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id     NUMBER         NOT NULL,
    fecha         DATE           NOT NULL,
    transaccion   VARCHAR2(30)   NOT NULL,
    monto         NUMBER(14, 2)  NOT NULL,
    descripcion   VARCHAR2(200)  NOT NULL,
    estado        VARCHAR2(20)   NOT NULL,
    CONSTRAINT uq_movimiento_anual_clave UNIQUE (cuenta_id, fecha, transaccion, monto, descripcion)
)
/

CREATE TABLE estado_cuenta_anual (
    id                     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id              NUMBER         NOT NULL,
    anio                   NUMBER         NOT NULL,
    total_depositos        NUMBER(14, 2)  NOT NULL,
    total_retiros          NUMBER(14, 2)  NOT NULL,
    saldo_neto             NUMBER(14, 2)  NOT NULL,
    cantidad_movimientos   NUMBER         NOT NULL,
    CONSTRAINT uq_estado_cuenta_anual UNIQUE (cuenta_id, anio)
)
/
